receivers:
  # Collect host metrics from the local system
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      network:

  # Collect internal telemetry data from the Exporter itself
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-exporter-internal'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']  # Internal telemetry endpoint

processors:
  batch:
    timeout: 10s
    send_batch_size: 512
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
  routing:
    from_attribute: metrics_type 
    attribute_source: context
    table:
      - value: "prometheus"
        exporters: [influxdb/prometheus]
      - value: "default"
        exporters: [influxdb/default]
  resource:
    attributes:
      - action: insert
        key: metrics_type
        value: default 

extensions:
  health_check: 
  pprof:
  zpages:

exporters:
  # Default InfluxDB Exporter
  influxdb/default:
    endpoint: http://influxdb2:8086
    org: docs
    bucket: monitordb
    token: 1clX8gJMWU9hlVZy4QcKFRAxN9_Y-W_X1HquXdMFRtKHPAKq3pHolHKwOuMv0qYNg8V5o36QeG6zMInsWfMZoA== 
    metrics_schema: telegraf-prometheus-v1
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  # InfluxDB Exporter for Prometheus Metrics
  influxdb/prometheus:
    endpoint: http://influxdb2:8086
    org: docs
    bucket: otel-exporter
    token: 1clX8gJMWU9hlVZy4QcKFRAxN9_Y-W_X1HquXdMFRtKHPAKq3pHolHKwOuMv0qYNg8V5o36QeG6zMInsWfMZoA== 
    metrics_schema: telegraf-prometheus-v1
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    metrics/host:
      receivers: [hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [influxdb/default]

    # Prometheus Metrics Pipeline
    metrics/prometheus:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [influxdb/prometheus]
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888


